services:
  - type: web
    name: tretyakov-coach-backend
    runtime: python
    repo: https://github.com/PivoGameDev/tretyakov-coach
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
